---

- hosts: 192.168.222.139

  tasks:
  - name: Installation du serveur Apache et PHP
    yum:
     name: "{{ item }}"
     state: present
    loop:
      - httpd
      - php
      - nano
      - mariadb-server

  - name: DÃ©marrage du serveur apache
    systemd:
     name: "{{ item }}"
     state: started
    loop:
      - httpd
      - mariadb

  - name: Copie des fichiers php
    copy:
     src: "{{ item }}"
     dest: /var/www/html/
    loop:
     - create_db.php
     - create_table.php
    
  - name: Copie des fichiers php
    copy:
     src: "{{ item }}"
     dest: /var/www/html/
    loop:
     - create_db.php
     - create_table.php
     - getting_data.php
     - insert_data.php
